# num1=int(input("enter the num1:"))
# num2=int(input("enter the num2:"))
# num3=int(input("enter the num3:"))
# num4=int(input("enter the num4:"))
# num5=int(input("enter the num5:"))
# num6=int(input("enter the num6:"))
# num7=int(input("enter the num7:"))
# num8=int(input("enter the num8:"))
# set={num1, num2, num3, num4,num5,num6,num7,num8}
# print(set)
num1=int(input("enter the num1:"))
num2=int(input("enter the num2:"))
num3=int(input("enter the num3:"))
num4=int(input("enter the num4:"))
num5=(input("enter the num5:"))
num6=(input("enter the num6:"))
num7=(input("enter the num7:"))
num8=(input("enter the num8:"))
set={num1, num2, num3, num4,num5,num6,num7,num8}
print(set)